# Generated by Django 4.2 on 2023-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenna_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antenna',
            name='status',
            field=models.CharField(choices=[(1, 'Up'), (0, 'Down')], default='Up', max_length=100),
        ),
    ]
