# Generated by Django 4.2 on 2023-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenna_map', '0002_antenna_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='status',
            field=models.CharField(choices=[(1, 'Up'), (2, 'Down')], default='Up', max_length=10),
        ),
    ]
