# Generated by Django 4.2 on 2023-04-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antenna_map', '0004_remove_antenna_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antenna',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='antenna',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
